version: '3'
services:
  jaeger-all-in-one:
    image: jaegertracing/all-in-one:latest
    restart: always
    ports:
      - "16686:16686"
      - "14268"
      - "14250"
  
  zipkin-all-in-one:
    image: openzipkin/zipkin:latest
    restart: always
    ports:
      - "9411:9411"

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    restart: always
    volumes:
      - ./.docker/prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  otel-collector:
    image: otel/opentelemetry-collector:latest
    restart: always
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./.docker/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "1888:1888"   # pprof extension
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "4317:4317"   # OTLP gRPC receiver
      - "55679:55679" # zpages extension
    depends_on:
      - zipkin-all-in-one
      - jaeger-all-in-one

  servico-a:
    build:
      context: ./servico-a
      dockerfile: Dockerfile
    container_name: servico-a
    restart: always
    ports:
      - "8080:8080"
    environment:
      - HTTP_PORT=:8080
      - OTEL_SERVICE_NAME=servico-a
      - OTEL_EXPORTER_OTLP_ENDPOINT=otel-collector:4317
      - SERVICO_B_URL=http://servico-b:8081
    depends_on:
      - otel-collector
      - servico-b
  servico-b:
    build:
      context: ./servico-b
      dockerfile: Dockerfile
    container_name: servico-b
    restart: always
    ports:
      - "8081:8081"
    environment:
      - HTTP_PORT=:8081
      - OTEL_SERVICE_NAME=servico-b
      - OTEL_EXPORTER_OTLP_ENDPOINT=otel-collector:4317
      - WEATHER_API_KEY=bd35e922f218459ba2400748251911
    depends_on:
      - otel-collector
    